stages:
  preprocessing:
    cmd: PYTHONPATH="." python lib/preprocessing.py --config-path params.yaml
    params:
      - preprocessing
    deps:
      - lib/preprocessing.py
    outs:
      - data/preprocessing

  train:
    cmd: PYTHONPATH="." python lib/train.py --config-path params.yaml
    params:
      - train
    deps:
      - lib/train.py
      - data/preprocessing
    outs:
      - data/train

  eval:
    cmd: PYTHONPATH="." python lib/eval.py --config-path params.yaml
    params:
      - eval
    deps:
      - lib/eval.py
      - data/train
      - data/preprocessing
    outs:
      - data/eval
    metrics:
      - data/metrics.json
